monitor.bluez.rules = [
  {
    matches = [
      {
        node.name = "bluez_input.94_DB_56_6E_85_E0.0"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
        priority.driver = 0
        priority.session = 0
      }
    }
  }
]
