[Service]
ExecStartPost=/bin/sh -c 'systemctl --user set-environment SSH_AUTH_SOCK=%t/ssh-agent.socket'
ExecStopPost=/bin/sh -c 'systemctl --user unset-environment SSH_AUTH_SOCK'

[Install]
WantedBy=default.target
