# remove quiet splash
LINUX_OPTIONS=" ${LINUX_OPTIONS} "
LINUX_OPTIONS="${LINUX_OPTIONS// quiet / }"
LINUX_OPTIONS="${LINUX_OPTIONS// splash / }"

LINUX_OPTIONS+=" plymouth.enable=0 disablehooks=plymouth "
