d	/var/lib/hass-ssh-shutdown	0700	hass-ssh-shutdown	hass-ssh-shutdown	-
d	/var/lib/hass-ssh-shutdown/.ssh	0700	hass-ssh-shutdown	hass-ssh-shutdown	-
f	/var/lib/hass-ssh-shutdown/.ssh/authorized_keys	0600	hass-ssh-shutdown	hass-ssh-shutdown	-
